package com.example.healthconnect.utils.database;

import android.annotation.SuppressLint;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class MockDataGenerator {
    public static void generateMockData() {
        List<Patient> patients = new ArrayList<>();

        for (int i = 1; i <= 50; i++) {
            Patient patient = new Patient(
                    0, // ID will be auto-generated by the database
                    "Patient " + i,
                    getRandomDateOfBirth(),
                    i % 2 == 0 ? "Male" : "Female",
                    "123-456-789" + i,
                    "patient" + i + "@example.com",
                    160 + Math.random() * 20, // Random height between 160cm and 180cm
                    50 + Math.random() * 40  // Random weight between 50kg and 90kg
            );
            long patientId = Database.addPatient(patient);

            if (patientId != -1) {
                patient.setId((int) patientId); // Update the patient ID with the database-generated ID
                patients.add(patient);
            }
        }

        for (int i = 1; i <= 200; i++) {
            Patient patient = patients.get(i % patients.size()); // Assign appointment to a random patient
            @SuppressLint("DefaultLocale") Appointment appointment = new Appointment(
                    0, // ID will be auto-generated by the database
                    patient,
                    "Routine Checkup",
                    String.format("2024-11-%02d", (i % 30) + 1), // Random date in November 2024
                    "09:30 AM",
                    "",
                    "",
                    "",
                    false
            );
            Database.addAppointment(appointment);
        }
    }

    private static int getRandomDateOfBirth() {
        Random random = new Random();

        int year = 1950 + random.nextInt(51); // Year between 1950 and 2000
        int month = 1 + random.nextInt(12);  // Month between 1 and 12
        int day = getRandomDayForMonth(month, year, random);

        // Combine year, month, and day into a single integer in YYYYMMDD format
        return year * 10000 + month * 100 + day;
    }

    private static int getRandomDayForMonth(int month, int year, Random random) {
        int maxDay;

        if (month == 2) {
            // Check for leap year
            maxDay = (year % 4 == 0 && (year % 100 != 0 || year % 400 == 0)) ? 29 : 28;
        } else if (month == 4 || month == 6 || month == 9 || month == 11) {
            maxDay = 30;
        } else {
            maxDay = 31;
        }

        return 1 + random.nextInt(maxDay); // Random day between 1 and maxDay
    }
}
